### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by MakonnenMak** [MakonnenMak/SimpleTex#11]
We have a reference, but no label it can refer to - assuming we were using LaTex rules for this. We also will need corresponding unit and integrations tests if we proceed.

**Comment by yonathanF** [comment]
Hm, yeah we need to add these in the lexer before we move to the parser. Idk how we forgot it

**Comment by yonathanF** [comment]
It seems like only the section would benefit from this addition since images come with their own label. We could match a label using something like 

```
^\\label\\{.+\\}\n
```
