### ISSUE TITLE
Lexer Refactor

### ISSUE THREAD

**Issue by MakonnenMak** [MakonnenMak/SimpleTex#12]
We're using the Lexer to parse too many details. This led to an inconsistent representation of our grammar when implementing the Parser as well as a lot of repetitive code. 

Refactor lexer to only parse for the specific tokens in our grammar.

**Comment by yonathanF** [comment]
# Mak tests

- [ ] braceR: 
- [ ] braceL: 
- [ ] parenL: 
- [ ] parenR: 

# Yoni tests

- [ ] squareL:
- [ ] squareR:
- [ ] exclam:

**Comment by MakonnenMak** [comment]
Closing issue. Previous comment listing tests was moved to #13
