### ISSUE TITLE
Lexer unit tests

### ISSUE THREAD

**Issue by yonathanF** [MakonnenMak/SimpleTex#13]
@MakonnenMak
- [x] SQUAREL
- [x] SQUARER
- [x] EXSQUARE

@yonathanF
- [x] BRACEL
- [x] BRACER
- [x] PARENL
- [x] PARENR

**Comment by MakonnenMak** [comment]
Completed tests in the **makonnen_tests** branch. I'll keep my work there till we merge this weekend.

**Comment by yonathanF** [comment]
Should be complete now
