### ISSUE TITLE
Lexer Integration

### ISSUE THREAD

**Issue by yonathanF** [MakonnenMak/SimpleTex#9]
@yonathanF
# Section integration 

- [x] section with plaintext content
- [x] section with large plaintext content
- [x] section with bold text and plaintext
- [x] section with italics text and plaintext
- [x] section with bolditalics text and plaintext
- [x] section with citations and plaintext
- [x] section with references and plaintext
- [x] section with equations and plaintext

@MakonnenMak
## Section with layout (one test)
- section with layout and with content:
  * plaintext content
  * large plaintext content
  * bold text and plaintext
  * italics text and plaintext
  * bolditalics text and plaintext
  * citations and plaintext
  * references and plaintext
  * equations and plaintext

# Subsection integration 

- [x] subsection with plaintext content
- [x] subsection with large plaintext content
- [x] subsection with bold text and plaintext
- [x] subsection with italics text and plaintext
- [x] subsection with bolditalics text and plaintext
- [x] subsection with citations and plaintext
- [x] subsection with references and plaintext
- [x] subsection with equations and plaintext

**Comment by yonathanF** [comment]
Unapply for List is maxed at 22 arguments so we will need to find a different of way testing that it realistically parses large content. I have it with 16 words right now.

**Comment by MakonnenMak** [comment]
Grouped text-modifiers like bold and italics together in one class then the _tags(?)_ like ref in another. Not sure if we discussed how we wanted to structure the code here.

**Comment by yonathanF** [comment]
reference and citation are sensitive to spacing around braces. so something like {hello} would parse into a string "{hello}" instead of braceL hello braceR. I think we should be fine for the first milestone tho
